### ISSUE TITLE
Host project has bad packages.config reference

### ISSUE THREAD

**Issue by kalanbates** [thinktecture/Thinktecture.IdentityManager.MembershipReboot#8]
I just pulled the source for the repository and the solution failed to build.
```
Build Error: "Unable to find version '1.0.0-pre-20141031' of package 'Thinktecture.IdentityManager'"
```
What version of IdM should be referenced by the Host project's packages.config?
(This same error occurred for the IdentityServer.MembershipReboot project for me yesterday)

To get around this, I removed the reference in packages.config, rebuilt from source, and made a hard library reference in IdentityManager to IdentityManager.MembershipReboot.dll

**Comment by brockallen** [comment]
Ty dev branch.

**Comment by kalanbates** [comment]
dev builds.  
Thanks.  
Are there any other Thinktecture repos you can think of that I should be currently working from dev?

**Comment by kalanbates** [comment]
Related yet slightly tangential:  I'm trying to put together my own CustomUser implementation inside my IdentityManager Host project and from the Thinktecture.IdentityManager.Host.CustomUser implementation in this repository, it indicates that it inherits BrockAllen.MembershipReboot.Relational.RelationalUserAccount.

When I go to your MembershipReboot repositories, I see no Relational namespace.  Where should I be looking for RelationalUserAccount?

**Comment by brockallen** [comment]
Right now we're in flux and about to RC IdentityServer, so mygets are best best until next week when we RC. Once we RC, then IdentityManager will get some more attention.

As for MR -- you should not need to build a custom build of it. Again, in the coming weeks some more time will be spent and thus more up to date samples.

**Comment by brockallen** [comment]
This should now be fixed. Thanks.
